logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG
    me.synology.hajubal: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:userservice;MODE=MySQL
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        show-sql: true